config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # READ
  get 'tasks', to: 'tasks#index'

  # CREATE
  get 'tasks/new', to: 'tasks#new', as: :new_task
  post 'tasks', to: 'tasks#create'

  # UPDATE
  get 'tasks/:id/edit', to: 'tasks#edit', as: :edit_task
  patch 'tasks/:id', to: 'tasks#update', as: :task

  # READ
  get 'tasks/:id', to: 'tasks#show'

  # DELETE
  delete 'tasks/:id', to: 'tasks#destroy'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  def index
    @tasks = Task.all
  end

  def show
  end

  def destroy
    @task.destroy

    redirect_to tasks_path
  end

  def new
    # empty template for form_for view helper
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)

    if @task.save
      # no specific view for create
      redirect_to task_path(@task)
    else
      # inform user that restaurant is not valid
    end
  end

  def edit
  end

  def update
    @task.update(task_params)

     # no specific view for update
    redirect_to task_path(@task)
  end

  private

  def set_task
    # KEEP IT DRY, this method is called thanks to before_action callback (see top)
    @task = Task.find(params[:id])
  end

  def task_params
    # to avoid malicious users to corrupt HTML forms
    params.require(:task).permit(:title, :details, :completed)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_controller_helper.rb
module TasksControllerHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://kit.fontawesome.com/7fd1e1aa98.js" crossorigin="anonymous"></script>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_for task do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :details %>
    <%= f.text_field :details, class: 'form-control' %>
  </div>
  <%= f.submit class: 'btn btn-primary' %>
<% end %>

app/views/tasks/edit.html.erb
<%= render 'form', task: @task %>

app/views/tasks/index.html.erb
<h4>Tasks</h4>
<ul style="list-style: none;">
  <% @tasks.each do |task| %>
    <li>
      <% if task.completed? %>
      <i class="far fa-check-square"></i>
      <% else %>
      <i class="far fa-square"></i>
      <% end %>
      <%= link_to task.title, task_path(task)%>
    </li>
  <% end %>
</ul>

<p><%= link_to 'new', new_task_path %></p>

app/views/tasks/new.html.erb
<%= form_for @task do |f| %>
    <%= f.label :title %>
    <%= f.text_field :title %>
    <%= f.label :details %>
    <%= f.text_field :details %>
  <%= f.submit %>
<% end %>

<p><%= link_to 'Home', tasks_path %></p>

app/views/tasks/show.html.erb
<h1>
  <% if @task.completed? %>
    <i class="far fa-check-square"></i>
  <% else %>
    <i class="far fa-square"></i>
  <% end %>
  <%= @task.title %>
</h1>

<h1><%= @task.details %></h1>


<p>
  <%= link_to 'delete task',
              task_path(@task),
              method: :delete,
              data: { confirm: 'Are you sure?' } %>
</p>

<p><%= link_to 'Home', tasks_path %></p>
<p><%= link_to 'edit', edit_task_path %></p>